
services:
    mosquito:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        restart: unless-stopped
        volumes:
            - ./mosquitto/conf:/mosquitto/conf
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/logs:/mosquitto/logs
